CREATE TABLE product (
ID UUID PRIMARY KEY,
NAME VARCHAR(255) NOT NULL,
DESCRIPTION TEXT,
IMAGE_URL VARCHAR(255),
PRICE DOUBLE PRECISION
);

CREATE TABLE CATEGORY (
ID SERIAL PRIMARY KEY,
NAME VARCHAR(255) NOT NULL,
CREATION_DATE TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE PRODUCT_CATEGORY (
PRODUCT_ID UUID NOT NULL,
CATEGORY_ID SERIAL NOT NULL,
PRIMARY KEY (PRODUCT_ID, CATEGORY_ID),
FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID) ON DELETE CASCADE,
FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY (ID) ON DELETE CASCADE
);

CREATE TABLE ADDRESS (
ID SERIAL PRIMARY KEY,
STREET VARCHAR(255) NOT NULL,
CITY VARCHAR(255) NOT NULL,
STATE VARCHAR(2) NOT NULL,
ZIP_CODE VARCHAR(10) NOT NULL
);


CREATE TABLE PERSON (
ID BIGSERIAL PRIMARY KEY,
CPF VARCHAR(11) NOT NULL,
NAME VARCHAR(100) NOT NULL,
BIRTH DATE NOT NULL,
EMAIL VARCHAR(255) NOT NULL
);

ALTER TABLE ADDRESS
ADD COLUMN PERSON_ID BIGINT NOT NULL;

ALTER TABLE ADDRESS
ADD CONSTRAINT FK_ADDRESS_PERSON
FOREIGN KEY (PERSON_ID)
REFERENCES PERSON(ID);

CREATE TABLE "USER" (
ID SERIAL PRIMARY KEY,
USERNAME VARCHAR(255) NOT NULL,
PASSWORD VARCHAR(255) NOT NULL
);

ALTER TABLE PERSON
ADD COLUMN USER_ID INT UNIQUE,
ADD CONSTRAINT FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES "USER"(ID);