version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: meu-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: meu_banco
    volumes:
      - ./data:/var/lib/postgresql/data
